BOOKS = {
    "1peter": {
        "display_name": "1 Peter",
        "reference_name": "1 Peter",
        "api_book_id": 60,
        "chapter_start": 1,
        "chapter_end": 5,
        "accent": "#003399",
        "csv_path": "data/verses/1peter.csv",
        "output_dir": "output/1_peter",
    },
    "james": {
        "display_name": "James",
        "reference_name": "James",
        "api_book_id": 59,
        "chapter_start": 1,
        "chapter_end": 5,
        "accent": "#7A2E2E",
        "csv_path": "data/verses/james.csv",
        "output_dir": "output/james",
    },
    "colossians": {
        "display_name": "Colossians",
        "reference_name": "Colossians",
        "api_book_id": 51,
        "chapter_start": 1,
        "chapter_end": 4,
        "accent": "#556B2F",
        "csv_path": "data/verses/colossians.csv",
        "output_dir": "output/colossians",
    },
    "1john": {
        "display_name": "1 John",
        "reference_name": "1 John",
        "api_book_id": 62,
        "chapter_start": 1,
        "chapter_end": 5,
        "accent": "#8B5E34",
        "csv_path": "data/verses/1_john.csv",
        "output_dir": "output/1_john",
    },
    "sermon_on_the_mount": {
        "display_name": "Sermon on the Mount",
        "reference_name": "Matthew",
        "api_book_id": 40,
        "chapter_start": 5,
        "chapter_end": 7,
        "accent": "#6B4F2A",
        "csv_path": "data/verses/sermon_on_the_mount.csv",
        "output_dir": "output/sermon_on_the_mount",
    },
    "psalm_1": {
        "display_name": "Psalm 1",
        "reference_name": "Psalm",
        "api_book_id": 19,
        "chapter_start": 1,
        "chapter_end": 1,
        "accent": "#4C6A7D",
        "csv_path": "data/verses/psalm_1.csv",
        "output_dir": "output/psalm_1",
    },
    "hebrews_11": {
        "display_name": "Hebrews 11",
        "reference_name": "Hebrews",
        "api_book_id": 58,
        "chapter_start": 11,
        "chapter_end": 11,
        "accent": "#7B3F00",
        "csv_path": "data/verses/hebrews_11.csv",
        "output_dir": "output/hebrews_11",
    },
    "exodus_20": {
        "display_name": "Exodus 20",
        "reference_name": "Exodus",
        "api_book_id": 2,
        "chapter_start": 20,
        "chapter_end": 20,
        "accent": "#4B5563",
        "csv_path": "data/verses/exodus_20.csv",
        "output_dir": "output/exodus_20",
    },
}